# DELETE http://localhost:3001/api/persons/4 HTTP/1.1
# content-type: application/json

# {
#     "name": "sample",
#     "time": "Wed, 21 Oct 2015 18:27:50 GMT"
# }


# DELETE http://localhost:3001/persons/5eaa6c39c48e8b17803810f1 HTTP/1.1
# content-type: application/json



PUT http://localhost:3001/api/persons/5eaa9701c918d6625843a792 HTTP/1.1
content-type: application/json

{
    "name": "Ville",
    "number": "2"
}


# GET http://localhost:3001/api/persons